### ISSUE TITLE
world freezing cause of issue unkown 

### ISSUE THREAD

**Issue by Thepal117** [Vetpetmon-Labs/Wyrms-of-Nyrus-Hub#2]
whenever i load a new world my game freezes and i have to forcefully shut it down  
since ive messed with the configs a few times ill add all relevant logs
[Uploading crash-2023-07-05_16.21.58-server.txt…]()

[crash-2023-07-05_15.33.30-server.txt](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/files/11962781/crash-2023-07-05_15.33.30-server.txt)
[crash-2023-07-05_16.12.06-server.txt](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/files/11962783/crash-2023-07-05_16.12.06-server.txt)

**Comment by Vetpetmon** [comment]
Good first issue, investigating immediately.

**Comment by Vetpetmon** [comment]
Should now be fixed in 0.3.43, which is currently out.

**Comment by Vetpetmon** [comment]
There seems to still be an issue. Investigating further.

**Comment by Vetpetmon** [comment]
This issue has mutated:

```
[20:10:28] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_351]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_351]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at com.vetpetmon.wyrmsofnyrus.WyrmVariables$WorldSavedDataSyncMessageHandler.lambda$onMessage$1(WyrmVariables.java:145) ~[WyrmVariables$WorldSavedDataSyncMessageHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 12 more
```

Not a fatal crash any longer, but at least much better than what was happening before. This issue was not happening with the Aether dimension ID or the Twilight Forest dimension ID, this could be a specific mod incompatibility.

**Comment by Vetpetmon** [comment]
This error is only one-time and non-fatal, the file generates as expected. The reason you are crashing is likely from not updating Wyrms of Nyrus to 0.3.43: https://modrinth.com/mod/wyrms/version/0.3.43
